name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install leiningen
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: 1.10.3.905

      - name: Test
        run: clojure -X:dev
